<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
]>
<gamelist>
	<game>
		<name>[MSX] MoonDriver songs</name>
		<driver type="generic">msx</driver>
		<options>
			<option name="init_pc"    value="0x0100"/>
			<option name="mdata_addr" value="0x10000"/>
			<option name="mdata_size" value="0x10000"/>
			<option name="mfile_size" value="0x10000"/>
			<option name="use_opl4"   value="0x01"/>
			<option name="opl4_mix"   value="0x100"/>
			<option name="clock_mul"  value="0x06"/>
		</options>
		<romlist archive="moondrv">
			<rom type="code" offset="0x0100">LOADER</rom>
			<rom type="code" offset="0x4000">moon_hoot.bin</rom>
			<rom type="bgm" offset="0x00">SONG.MDR</rom>
		</romlist>
		<titlelist>
			<title code="0x00">SONG.MDR</title>
		</titlelist>
	</game>

<!-- ================ END ================ -->
</gamelist>
